codepkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MyPlace_Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Imported property data from MyPlace that has been automatically matched to the property record in Salesforce</description>
        <inlineHelpText>Imported property data from MyPlace that has been automatically matched to the property record in Salesforce</inlineHelpText>
        <label>MyPlace Property</label>
        <referenceTo>MyPlace_Property__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_2__c</fullName>
        <label>Number of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parcel_Number_2__c</fullName>
        <label>Parcel Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Built_2__c</fullName>
        <label>Year Built</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_2__c</fullName>
        <label>Zip</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/MyPlace_Property__c.object
<CustomObject>
    <description>Public data imported from the Cuyahoga County FTP that is relevant to HHP. Imported into Salesforce to save HHP users from manually going into MyPlace. Data must be updated annually using a data load</description>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Year the house was built</description>
        <inlineHelpText>Year the house was built</inlineHelpText>
        <label>Age</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CITY__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEEDED_OWNER__c</fullName>
        <description>The owner of the property according to the deed</description>
        <inlineHelpText>The owner of the property according to the deed</inlineHelpText>
        <label>Deeded Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCCUPANCY__c</fullName>
        <description>Residential occupancy from MyPlace</description>
        <inlineHelpText>Residential occupancy from MyPlace</inlineHelpText>
        <label>Occupancy</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PARCEL_ID__c</fullName>
        <description>Parcel ID from MyPlace. Same as the parcel number / property number, but without dashes. Used as external ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Parcel ID from MyPlace used to update data</inlineHelpText>
        <label>MyPlace Parcel ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>STATE__c</fullName>
        <description>State of the MyPlace Property. Not always provided in MyPlace Data, but unless if something incredible happens, this will always be Ohio</description>
        <inlineHelpText>State of the MyPlace Property. Not always provided in MyPlace Data, but unless if something incredible happens, this will always be Ohio.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STREET_DIR__c</fullName>
        <description>Street direction, like the West in W 117th St</description>
        <inlineHelpText>Street direction, like the West in W 117th St</inlineHelpText>
        <label>Street Direction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STREET_NAME__c</fullName>
        <description>Street name without type of street or direction</description>
        <inlineHelpText>Street name without type of street or direction</inlineHelpText>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STREET_NUMBER__c</fullName>
        <description>Number of the address</description>
        <inlineHelpText>Number of the address</inlineHelpText>
        <label>Street Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STREET_SUFFIX__c</fullName>
        <description>The actual type of street, like St, Ave, Ln, Rd, Ct, etc.</description>
        <inlineHelpText>The actual type of street, like St, Ave, Ln, Rd, Ct, etc.</inlineHelpText>
        <label>Street Suffix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITS__c</fullName>
        <description>Number of units</description>
        <inlineHelpText>Often 0 if there the property is not split into units</inlineHelpText>
        <label>Number of Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZIP__c</fullName>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MyPlace Property</label>
    <nameField>
        <label>MyPlace Parcel Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyPlace Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/AccountTriggerControllerTest.cls
@IsTest
public class AccountTriggerControllerTest {
	private static String PROPERTY_PARCEL_NUMBER = '001-01-011';
	private static String PROPERTY_OWNER_NAME = 'CAPOZIELLO, GREGORY & CANDICE';
	private static Integer PROPERTY_OCCUPANCY = 1;
	private static Integer PROPERTY_AGE = 1950;
	private static String PROPERTY_STREET_NUMBER = '11516';
	private static String PROPERTY_STREET_NAME = 'Edgewater';
	private static String PROPERTY_STREET_SUFFIX = 'Dr';
	private static String PROPERTY_ZIP = '44102';

	@IsTest
	static void beforeInsert_givenExactAddressAndZipMatch_shouldSetMyPlacePropertyAndRelatedFields() {
		String accountAddress = PROPERTY_STREET_NUMBER + ' ' + PROPERTY_STREET_NAME + ' ' + PROPERTY_STREET_SUFFIX;
		Account testAccount = new Account(
				Name = accountAddress,
				Zip_2__c = PROPERTY_ZIP
		);

		Test.startTest();
			insert testAccount;
		Test.stopTest();

		Account insertedTestAccount = [SELECT MyPlace_Property__c, Parcel_Number_2__c, Number_of_Units_2__c, Year_Built_2__c
										FROM Account
										WHERE Name = :accountAddress];

		MyPlace_Property__c testMyPlaceProperty = [SELECT Id, Name, OCCUPANCY__c, AGE__c
													FROM MyPlace_Property__c
													WHERE Name = :PROPERTY_PARCEL_NUMBER];

		System.assertEquals(testMyPlaceProperty.Id, insertedTestAccount.MyPlace_Property__c,
				'The MyPlace Property lookup on the Account should be set to the Id of the MyPlace Property record matching the Account\'s address.');
		System.assertEquals(testMyPlaceProperty.Name, insertedTestAccount.Parcel_Number_2__c,
				'The Parcel Number field on the Account should be set to the Name of the MyPlace Property record matching the Account\'s address.');
		System.assertEquals(testMyPlaceProperty.OCCUPANCY__c, insertedTestAccount.Number_of_Units_2__c,
				'The Number of Units field on the Account should be set to the Occupancy of the MyPlace Property record matching the Account\'s address'
						+ ' when the Units field on the MyPlace Property is 0 or null.');
		System.assertEquals(String.valueOf(testMyPlaceProperty.AGE__c), insertedTestAccount.Year_Built_2__c,
				'The Year Built field on the Account should be set to the Age of the MyPlace Property record matching the Account\'s address.');
	}

	@IsTest
	static void beforeInsert_givenCloseAddressAndZipMatch_shouldTryToSetMyPlacePropertyViaLevenshteinDistance() {
		// Not an exact address match, but close (ie, Drive and not Dr)
		String accountAddress = PROPERTY_STREET_NUMBER + ' ' + PROPERTY_STREET_NAME + ' Drive';
		Account testAccount = new Account(
				Name = accountAddress,
				Zip_2__c = PROPERTY_ZIP
		);

		Test.startTest();
			insert testAccount;
		Test.stopTest();

		Account insertedTestAccount = [SELECT MyPlace_Property__c, Parcel_Number_2__c, Number_of_Units_2__c, Year_Built_2__c
										FROM Account
										WHERE Name = :accountAddress];

		MyPlace_Property__c testMyPlaceProperty = [SELECT Id, Name, OCCUPANCY__c, AGE__c
													FROM MyPlace_Property__c
													WHERE Name = :PROPERTY_PARCEL_NUMBER];

		System.assertEquals(testMyPlaceProperty.Id, insertedTestAccount.MyPlace_Property__c,
				'The MyPlace Property lookup on the Account should be set to the Id of the MyPlace Property record matching the Account\'s address.');
		System.assertEquals(testMyPlaceProperty.Name, insertedTestAccount.Parcel_Number_2__c,
				'The Parcel Number field on the Account should be set to the Name of the MyPlace Property record matching the Account\'s address.');
		System.assertEquals(testMyPlaceProperty.OCCUPANCY__c, insertedTestAccount.Number_of_Units_2__c,
				'The Number of Units field on the Account should be set to the Occupancy of the MyPlace Property record matching the Account\'s address'
						+ ' when the Units field on the MyPlace Property is 0 or null.');
		System.assertEquals(String.valueOf(testMyPlaceProperty.AGE__c), insertedTestAccount.Year_Built_2__c,
				'The Year Built field on the Account should be set to the Age of the MyPlace Property record matching the Account\'s address.');
	}

	@IsTest
	static void beforeInsert_givenWrongAddressAndZipMismatch_shouldNotMatch() {
		String accountAddress = '1234 Wrong Street';
		Account testAccount = new Account(
				Name = accountAddress,
				Zip_2__c = '12345'
		);

		Test.startTest();
			insert testAccount;
		Test.stopTest();

		Account insertedTestAccount = [SELECT MyPlace_Property__c, Parcel_Number_2__c, Number_of_Units_2__c, Year_Built_2__c
										FROM Account
										WHERE Name = :accountAddress];

		System.assertEquals(null, insertedTestAccount.MyPlace_Property__c,
				'The MyPlace Property lookup on the Account should not be set if a matching MyPlace Property does not exist for the given address and zip.');
		System.assertEquals(null, insertedTestAccount.Parcel_Number_2__c,
				'The Parcel Number field on the Account should not be automatically set if a matching MyPlace Property does not exist for the given address and zip.');
		System.assertEquals(null, insertedTestAccount.Number_of_Units_2__c,
				'The Number of Units field on the Account should not be automatically set if a matching MyPlace Property does not exist for the given address and zip.');
		System.assertEquals(null, insertedTestAccount.Year_Built_2__c,
				'The Year Built field on the Account should not be automatically set if a matching MyPlace Property does not exist for the given address and zip.');
	}

	@TestSetup
	static void createMyPlacePropertyForInsert() {
		MyPlace_Property__c testMyPlaceProperty = new MyPlace_Property__c(
				Name = PROPERTY_PARCEL_NUMBER,
				PARCEL_ID__c = '101011',
				DEEDED_OWNER__c = PROPERTY_OWNER_NAME,
				UNITS__c = 0,
				OCCUPANCY__c = PROPERTY_OCCUPANCY,
				AGE__c = PROPERTY_AGE,
				STREET_NUMBER__c = PROPERTY_STREET_NUMBER,
				STREET_DIR__c = null,
				STREET_NAME__c = PROPERTY_STREET_NAME,
				STREET_SUFFIX__c = PROPERTY_STREET_SUFFIX,
				CITY__c = 'Cleveland',
				STATE__c = 'OH',
				ZIP__c = PROPERTY_ZIP
		);

		insert testMyPlaceProperty;
	}
}