codepkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MyPlace_Property_Owner__c</fullName>
        <description>Name of the property owner pulled from the associated MyPlace Property</description>
        <formula>MyPlace_Property__r.DEEDED_OWNER__c</formula>
        <inlineHelpText>Name of the property owner pulled from the associated MyPlace Property</inlineHelpText>
        <label>MyPlace Property Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MyPlace_Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Imported property data from MyPlace that has been automatically matched to the property record in Salesforce</description>
        <inlineHelpText>Imported property data from MyPlace that has been automatically matched to the property record in Salesforce</inlineHelpText>
        <label>MyPlace Property</label>
        <referenceTo>MyPlace_Property__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_2__c</fullName>
        <label>Number of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parcel_Number_2__c</fullName>
        <label>Parcel Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Owner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Property Owner)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_Built_2__c</fullName>
        <label>Year Built</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_2__c</fullName>
        <label>Zip</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Inquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Client Contact</label>
    <nameField>
        <displayFormat>INQ-{000000}</displayFormat>
        <label>Client Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/MyPlace_Property__c.object
<CustomObject>
    <description>Public data imported from the Cuyahoga County FTP that is relevant to HHP. Imported into Salesforce to save HHP users from manually going into MyPlace. Data must be updated annually using a data load</description>
    <fields>
        <fullName>AGE__c</fullName>
        <description>Year the house was built</description>
        <inlineHelpText>Year the house was built</inlineHelpText>
        <label>Age</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>The first line of the address put together from its individual parts</description>
        <formula>STREET_NUMBER__c + &apos; &apos; +  IF(ISBLANK(STREET_DIR__c), &apos;&apos;,  STREET_DIR__c + &apos; &apos;) + STREET_NAME__c + &apos; &apos; + STREET_SUFFIX__c</formula>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CITY__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEEDED_OWNER__c</fullName>
        <description>The owner of the property according to the deed</description>
        <inlineHelpText>The owner of the property according to the deed</inlineHelpText>
        <label>Deeded Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCCUPANCY__c</fullName>
        <description>Residential occupancy from MyPlace</description>
        <inlineHelpText>Residential occupancy from MyPlace</inlineHelpText>
        <label>Occupancy</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STREET_NUMBER__c</fullName>
        <description>Number of the address</description>
        <inlineHelpText>Number of the address</inlineHelpText>
        <label>Street Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITS__c</fullName>
        <description>Number of units</description>
        <inlineHelpText>Often 0 if there the property is not split into units</inlineHelpText>
        <label>Number of Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZIP__c</fullName>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MyPlace Property</label>
    <nameField>
        <label>MyPlace Parcel Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyPlace Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/AccountTriggerController.cls
public class AccountTriggerController {

	public void beforeInsert(List<Account> newAccounts) {
		setMyPlaceDataOnAccounts(newAccounts);
	}

	public void afterInsert(List<Account> newAccounts) {
		createClientContactsForAccounts(newAccounts);
	}

	private void setMyPlaceDataOnAccounts(List<Account> newAccounts) {
		for (Account acc : newAccounts) {
			// Note: This is doing SOQL in a loop. getMyPlaceProperty() is not bulkified and cannot be bulkified.
			// Be careful when inserting more than a few Accounts
			MyPlace_Property__c matchingMyPlaceProperty = getMyPlaceProperty(acc);

			// Skip records where a MyPlace Property couldn't be matched
			if (matchingMyPlaceProperty == null) {
				continue;
			}

			acc.MyPlace_Property__c = matchingMyPlaceProperty.Id;
			acc.Parcel_Number_2__c = matchingMyPlaceProperty.Name; // Name on MyPlace_Property__c is the Parcel Number

			// If there isn't any number for the given units, use the occupancy instead
			if (matchingMyPlaceProperty.UNITS__c == null || matchingMyPlaceProperty.UNITS__c == 0) {
				acc.Number_of_Units_2__c = matchingMyPlaceProperty.OCCUPANCY__c;
			} else {
				acc.Number_of_Units_2__c = matchingMyPlaceProperty.UNITS__c;
			}

			// The Property Owner isn't being mapped here
			// Instead, it is being pulled up onto Account with a formula field, MyPlace_Property_Owner__c

			// The year is optional on the Heritage Home Consultation scheduling form.
			// If it's given, we don't want to overwrite it. As such, we only set it if it's blank
			if (String.isBlank(acc.Year_Built_2__c)) {
				acc.Year_Built_2__c = String.valueOf(matchingMyPlaceProperty.AGE__c);
			}
		}
	}

	// The MyPlace Property-setting code unfortunately cannot be bulkified. There are 550k MyPlace Properties records,
	// which would run into the SOQL record limit immediately if we tried to query all of them and then sort afterwards.
	// Returns null if the MyPlace Property can't be found
	private MyPlace_Property__c getMyPlaceProperty(Account accountToMatchProperty) {
		MyPlace_Property__c bestMatchMyPlaceProperty;
		String accountAddress = accountToMatchProperty.Name.toUpperCase();
		String accountStreetNumber = accountAddress.split(' ')[0];

		// Selecting by zip and street number to first to limit the number of MyPlace Property records we get
		// There's 550k records and that would run into the SOQL limit, so we unfortunately can't select all
		// While we could select by city as well, the county's data has a LOT of incorrect city names
		// There's some bad zip codes, but much fewer than the bad cities
		List<MyPlace_Property__c> possibleMyPlaceProperties = [
			SELECT Name, Address__c, STREET_NUMBER__c, CITY__c, ZIP__c, UNITS__c, OCCUPANCY__c, AGE__c, DEEDED_OWNER__c
			FROM MyPlace_Property__c
			WHERE ZIP__c = :accountToMatchProperty.Zip_2__c
				AND STREET_NUMBER__c = :accountStreetNumber
		];

		// The Levenshtein distance between two strings is the minimum number of single-character edits required to change one string into the other
		// It helps us find the best address match for the MyPlace Property
		// Starting it off impossibly high so the first MyPlace Property we check is a better match
		Integer bestMatchDistance = 999999999;
		for (MyPlace_Property__c possibleMyPlaceProperty : possibleMyPlaceProperties) {
			// Checking by upper case to get rid of distance issues from capitalization, which don't matter here
			String possibleMyPlacePropertyAddress = possibleMyPlaceProperty.Address__c.toUpperCase();
			// If we find the exact property, we're all done! No more looping
			if (possibleMyPlacePropertyAddress == accountAddress) {
				bestMatchMyPlaceProperty = possibleMyPlaceProperty;
				break;
			}

			Integer currentDistance = possibleMyPlacePropertyAddress.getLevenshteinDistance(accountAddress);
			if (currentDistance < bestMatchDistance) {
				bestMatchDistance = currentDistance;
				bestMatchMyPlaceProperty = possibleMyPlaceProperty;
			}
		}

		return bestMatchMyPlaceProperty;
	}

	private void createClientContactsForAccounts(List<Account> newAccounts) {
		List<Inquiry__c> clientContactsToCreate = new List<Inquiry__c>();
		for (Account insertedAccount : newAccounts) {
			Inquiry__c newClientContact = new Inquiry__c(
					NewProperty__c = insertedAccount.Id,
					Contact__c = insertedAccount.Property_Owner_2__c, //TODO: Property_Owner_2__c isn't being set yet
					Date__c = insertedAccount.CreatedDate,
					Note__c = 'Initial Inquiry'
			);
			clientContactsToCreate.add(newClientContact);
		}
		insert clientContactsToCreate;
	}
}