codepkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Owner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Property Owner)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/AccountDA.cls
public with sharing class AccountDA implements AccountDAI {
    public List<Account> getAccountsByNames(List<String> accountNames) {
        List<Account> accounts = [SELECT Id, Name, Property_Owner_2__c, City_2__c FROM Account WHERE Name IN :accountNames]; 
        return accounts;
    }

    public List<Account> getAccountsByIds(Set<Id> accountIds) {
        return [SELECT Id, Name, Property_Owner_2__c, City_2__c FROM Account WHERE Id IN :accountIds];
    }

    public void insertAccounts(List<Account> accountsToInsert) {
        insert accountsToInsert;
    }
}